### ISSUE TITLE
distribution of sites doesn't look like in the previous report

### ISSUE THREAD

**Issue by FabianRoger** [FabianRoger/AoB_Butterflies#11]
from the powerpoint:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5137092/104922090-84a25980-599a-11eb-9c26-ffc00e86400f.png">

What I get:

![image](https://user-images.githubusercontent.com/5137092/104922190-a7347280-599a-11eb-88bd-0000d79f3295.png)

Also not that I have 924 unique SiteIDs, teh porevious report mentiones 458. I have 683 from Länstyrelse and 241 from NILS / SLU.

**Comment by FabianRoger** [comment]
I realized that this is because the data I have do not have data from Kronobergs län. Should they?

**Comment by larspett** [comment]
No the ones you have are the only ones to analyze. Blekinge and Kronoberg left and Kalmar joined
