### ISSUE TITLE
Incorrect observations that should be filtered out

### ISSUE THREAD

**Issue by larspett** [FabianRoger/AoB_Butterflies#3]
I have gone through the validation file and identified these observations that would need verification but that are almost certainly incorrect. I suggest you add a filter that removes them before analyses

Species	                    County	Number of cases
Alkonblåvinge               T,F	               3
Asknätfjäril	                F	               1
Blomvisslare                   all	               6
Brun gräsfjäril	                E	               2
Ekspinnare	               all	               1
Fetörtsblåvinge	       all	               4
Gullvivefjäril	              T,F	               6
Friggas pärlemorfjäril    T,F	               2
Grönfläckig vitfjäril	       all	              30
Krattsnabbvinge	        T	               4
Kronärtsblåvinge	      SLU	       	       	1
Ljusgul höfjäril	               M,T	       	       	3
Turkos blåvinge	        all                    2
Violett guldvinge	        all		       16
Väpplingblåvinge	         T		         2
Mnemosynefjäril	         E	   	         1

These should be filtered away for CountyCode=14
Kartfjäril                        T,SLU	                  2

These should be filtered away for CountyCode=1
Midsommarblåvinge      SLU	                  2

**Comment by larspett** [comment]
Sorry the formatting of the "table" went away so everything just moved left, hopefully it should be possible to understand

**Comment by FabianRoger** [comment]
All should be removed now.

According to my data, there where 7 cases of the Gullvivefjäril and 19 cases of the Violett guldvinge that should be excluded (not 6 and 16)
