### ISSUE TITLE
Some dates are erronous

### ISSUE THREAD

**Issue by FabianRoger** [FabianRoger/AoB_Butterflies#4]
```
RMO$date[is.na(as.numeric(RMO$date))][is.na(as.Date(RMO$date[is.na(as.numeric(RMO$date))], format = "%Y-%m-%d"))]
```

This line of code gives you the dates that have (for some reason) not been transformed to numeric when importing from excel _and_ cannot be converted to date in the `%Y-%m-%d` format. 

The dates are `"2010-20-08" "2018-06-31"`

I guess the first date in `%Y-%d-%m`. The second date is impossible. replace it by `2018-07-01`?

**Comment by larspett** [comment]
Yes to both! I remember that 0631 from when we imported to our database
